### ISSUE TITLE
multiple custom validators with promises and not

### ISSUE THREAD

**Issue by jaaaco** [mprzodala/form-schema-validation#1]
Hi
I would like to report a problem (or I'm doing sth wrong):
```javascript
const validEmail = {
  validator(value) {
    return true;
  },
  errorMessage: 'Incorrect email address',
};

const validPassword = {
  validator(value) {
    return value.length >= 6;
  },
  errorMessage: 'Password must be at least 6 characters long',
};

const uniqueEmail = {
  validator(email) {
    return new Promise(resolve => {
      resolve(false)
    });
  },
  errorMessage: 'User with this email already exists',
};

const signUpSchema = new Schema({
  email: {
    type: String,
    validators: [validEmail, uniqueEmail],
  },
  password: {
    type: String,
    validators: [validPassword]
  },
});

```

signUpSchema.validate({ email, password }).then( errors => { ... } )

In case above uniqeEmail validator is called but validate().then() is resolved with no errors no matter what uniqueEmail validator returns

**Comment by jaaaco** [comment]
When I was trying to find a fix for that problem I was able to find out, that problem has sth to do with babel traspilation, when using your src code directly everything start to work corretly, my babel preset was:

```javascript
{
  "passPerPreset": true,
  "presets": [
    "es2015",
    "stage-0"
  ]
}
```

(node 8.0.0, npm 5.0.0)

**Comment by mprzodala** [comment]
Thanks for info I will check it today and give you know.

**Comment by mprzodala** [comment]
Fixed. Please check version 1.11.1
