### ISSUE TITLE
When label is given, use it as ErrorMessage ${key}?

### ISSUE THREAD

**Issue by leroy0211** [mprzodala/form-schema-validation#4]
The schema `label` key is currently not used anywhere, maybe that's a real issue but I'm not sure. 
My proposition is to use the label as fieldname (`key`) for the `ErrorMessages`, when the label is given. Because otherwise all messages will contain the name of the form fields. 

In my use case these names are just random numbers, and will display something like: 

`Field '21830' is required`

**Comment by mprzodala** [comment]
Good point I will look on it.

**Comment by mprzodala** [comment]
@leroy0211  Please try new version 1.10.0 there is support for labels in error message.

**Comment by leroy0211** [comment]
The `label` as fieldname is still not available in all messages. 
See: https://github.com/mprzodala/form-schema-validation/blob/master/src/Schema.js#L221
