### ISSUE TITLE
defaultValue wraps a list of defaultValues in an array

### ISSUE THREAD

**Issue by leroy0211** [mprzodala/form-schema-validation#6]
When you have a type validation which is an array, and you want to have multiple default values, the default values are wrapped inside an array

Example: 

```
{
    type: [String],
    label: 'Siblings',
    defaultValue: ['john','jane'],
    options: [... list of persons here]
}
```

The defaultValue in the schema will look like: `[['john', 'jane']]`. To determine if the defaultValue must be wrapped is only done by checking if the `type` is an array.

**Comment by mprzodala** [comment]
Fixed. Please check version 1.11.0. I was added value check.
