### ISSUE TITLE
falsified defaultValues are not accepted.

### ISSUE THREAD

**Issue by leroy0211** [mprzodala/form-schema-validation#7]
When you want to disable default values or want to "fake" it by using a falsified value, the default value will still be calculated. 

Example:
```
{
    type: [String],
    defaultValue: false,
    options: [... list of items]
}
```

You would expect there isn't a default value, but it's still the first one of the `options` list.

**Comment by mprzodala** [comment]
Fixed. Please check version 1.11.0. I was added disableDefaultValue flag that gives you posibility to disable default value for field and now defaultValue accept Boolan "false".
